#!/usr/bin/env php
<?php

	define('BASEPATH', 'system/');
	define('APPPATH', 'application/');

	switch (isset($_SERVER['ENVIRONMENT']) && $_SERVER['ENVIRONMENT']) {
		case '127.0.0.1':
			define('ENVIRONMENT', 'development');
		break;
		
		default:
			define('ENVIRONMENT', 'production');
		break;
	}

	chdir(dirname(__FILE__));
	require_once('application/third_party/doctrine/Doctrine.php'); 

	$setup = new Doctrine();
	$setup->setUpCommandLine();
	
?>
