<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcisessions extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ci_sessions', array(
             'session_id' => 
             array(
              'type' => 'string',
              'length' => 40,
              'fixed' => false,
              'unsigned' => false,
              'primary' => true,
              'autoincrement' => false,
              'notnull' => false,
             ),
             'ip_address' => 
             array(
              'type' => 'string',
              'length' => 16,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'default' => '0',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'user_agent' => 
             array(
              'type' => 'string',
              'length' => 120,
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
             ),
             'last_activity' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'fixed' => false,
              'unsigned' => true,
              'primary' => false,
              'default' => '0',
              'notnull' => true,
              'autoincrement' => false,
             ),
             'user_data' => 
             array(
              'type' => 'string',
              'fixed' => false,
              'unsigned' => false,
              'primary' => false,
              'notnull' => true,
              'autoincrement' => false,
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'session_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ci_sessions');
    }
}
